import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const errs=[]; p.on("pageerror",e=>errs.push(String(e)));
await p.addInitScript(()=>localStorage.clear());
await p.goto("http://localhost:5173",{waitUntil:"networkidle"});
await p.waitForSelector("canvas");
await p.getByRole("button",{name:"spectrum",exact:true}).click();
await p.getByPlaceholder("cue name").fill("rainbow");
await p.getByText("💾 save",{exact:false}).click();
await p.getByRole("button",{name:"solid",exact:true}).click();
await p.getByText("▶ rainbow",{exact:false}).click();
await p.waitForTimeout(600);
await p.screenshot({ path:"screenshots/cycle24-cues.png" });
await b.close();
console.log(errs.length?"ERRORS:\n"+errs.join("\n"):"cue save+recall ok");
