import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
const errs=[]; p.on("pageerror",e=>errs.push(String(e)));
await p.goto("http://localhost:5173",{waitUntil:"networkidle"});
await p.waitForSelector("canvas");
await p.getByRole("button",{name:"breathe",exact:true}).click();
await p.getByText("✨ ping",{exact:false}).click();
await p.waitForTimeout(450);
await p.screenshot({ path:"screenshots/cycle28-ripple.png" });
await p.getByText("✨ ping",{exact:false}).click();
await p.waitForTimeout(250);
await p.screenshot({ path:"screenshots/cycle28-ripple2.png" });
await b.close();
console.log(errs.length?"ERRORS:\n"+errs.join("\n"):"ripple ok");
