import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
const errs=[]; p.on("pageerror",e=>errs.push(String(e)));
await p.goto("http://localhost:5173",{waitUntil:"networkidle"});
await p.waitForSelector("canvas");
const ta = p.locator("textarea");
await ta.fill("all pattern solid\nzone high color #00aaff\nevery 4 color red");
await p.getByText("▶ run script",{exact:false}).click();
await p.waitForTimeout(1000);
await p.screenshot({ path:"screenshots/cycle20-llmscript.png" });
await b.close();
console.log(errs.length?"ERRORS:\n"+errs.join("\n"):"script ran, no errors");
